/*
 * This source file was generated by the Gradle 'init' task
 */
package com.atxbogart.trustedadvisor

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class App

fun main(args: Array<String>) {
    runApplication<App>(*args)
}
